backend:
depends_on: 
  - mysqlDatabase
build: 
  context: backend
  dockerfile: Dockerfile
ports:
  - "9090:9090"
restart: always
environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqlDatabase:3306/projectManager
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: password
networks:
      -common-network

mysqlDatabase:
image: mysql
restart: always
volumes:
  - db_data:/var/lib/mysql
environment:
  MYSQL_DATABASE: projectManager
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: password
networks:
      -common-network

#Docker Networks
networks:
    common-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
