name: CI Angular app through Github Actions
on: push
  branches:
    - develop
on: pull_request:
  branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=Chrome
      - name: Lint
        run: npm run lint