name: backend CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: build
        run: |
          cd PMBackend
          mvn clean compile
  tests:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: projectManagerTest
          MYSQL_ROOT_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: test
        run: |
          cd PMBackend
          mvn clean test